---
apiVersion: v1
kind: Namespace
metadata:
  name: diplom
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: diplom
spec:
  selector:
    app: diplom
  ports:
    - name: nginx-http
      protocol: TCP
      port: 80
      nodePort: 30080
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom
  namespace: diplom
  labels:
    app: diplom
    group: diplom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diplom
  template:
    metadata:
      namespace: diplom
      labels:
        app: diplom
        group: diplom
    spec:
      containers:
        - name: diplom
          image: lunezhev2.gitlab.yandexcloud.net:5050/and/diplom:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      # imagePullSecrets: 
      #   - name: registry-credentials-site
