---
- name: clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
  tags:
    - clickhouse

- name: lighthouse
  hosts: lighthouse
  roles:
    - lighthouse
  tags:
    - lighthouse

- name: vector
  hosts: vector
  roles:
    - vector
  tags:
    - vector
    