---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-netology
  labels:
    app: deploy-net
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deploy-net
  template:
    metadata:
      labels:
        app: deploy-net
    spec:
      containers:
      - name: nginx128
        image: nginx:1.28
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
          - name: HTTPS_PORT
            value: "10443"
        ports:
        - containerPort: 8080
        - containerPort: 10443

---

apiVersion: v1
kind: Service
metadata:
  name: service-netology
spec:
  selector:
    app: deploy-net
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool-http
      protocol: TCP
      port: 9002
      targetPort: 8080
