apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset-netology-read-log
  labels:
    app: node-logs
spec:
  selector:
    matchLabels:
      app: node-logs
  template:
    metadata:
      labels:
        app: node-logs
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: var-log
          mountPath: /var/log
      volumes:
      - name: var-log
        hostPath:
          path: /var/log
          type: ""