apiVersion: v1
kind: Service
metadata:
  name: service-netology-external
spec:
  selector:
    app: deploy-net
  ports:
    - name: nginx
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 30001
  type: NodePort